# Generated by Django 2.0.2 on 2018-04-16 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0002_bookinstance_borrower'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['last_name']},
        ),
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['title']},
        ),
        migrations.RemoveField(
            model_name='bookinstance',
            name='borrower',
        ),
    ]
